server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 10000
spring:
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_examsystem?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
  devtools:
    livereload:
      enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/